# Generated by Django 5.1.2 on 2024-10-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tbl_name',
            },
        ),
    ]
