# Generated by Django 5.1.2 on 2024-10-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_employee',
            table='tbl_employee',
        ),
    ]
